--------------------------------
-- Copyright (C) 2021-2025 CARTO
--------------------------------

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_MAKEELLIPSE
(GEOMETRY, FLOAT8, FLOAT8)
-- (center, xSemiAxis, ySemiAxis)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMGEOJSON(@@RS_SCHEMA@@.__MAKEELLIPSE(ST_ASGEOJSON($1)::VARCHAR(MAX), CAST($2 AS VARCHAR(MAX)), CAST($3 AS VARCHAR(MAX)), '0', 'kilometers', 64))
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_MAKEELLIPSE
(GEOMETRY, FLOAT8, FLOAT8, FLOAT8)
-- (center, xSemiAxis, ySemiAxis, angle)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMGEOJSON(@@RS_SCHEMA@@.__MAKEELLIPSE(ST_ASGEOJSON($1)::VARCHAR(MAX), CAST($2 AS VARCHAR(MAX)), CAST($3 AS VARCHAR(MAX)), CAST($4 AS VARCHAR(MAX)), 'kilometers', 64))
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_MAKEELLIPSE
(GEOMETRY, FLOAT8, FLOAT8, FLOAT8, VARCHAR(10))
-- (center, xSemiAxis, ySemiAxis, angle, units)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMGEOJSON(@@RS_SCHEMA@@.__MAKEELLIPSE(ST_ASGEOJSON($1)::VARCHAR(MAX), CAST($2 AS VARCHAR(MAX)), CAST($3 AS VARCHAR(MAX)), CAST($4 AS VARCHAR(MAX)   ), $5, 64))
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_MAKEELLIPSE
(GEOMETRY, FLOAT8, FLOAT8, FLOAT8, VARCHAR(10), INT)
-- (center, xSemiAxis, ySemiAxis, angle, units, steps)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMGEOJSON(@@RS_SCHEMA@@.__MAKEELLIPSE(ST_ASGEOJSON($1)::VARCHAR(MAX), CAST($2 AS VARCHAR(MAX)), CAST($3 AS VARCHAR(MAX)), CAST($4 AS VARCHAR(MAX)), $5, $6))
$$ LANGUAGE sql;
