----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE FUNCTION __S2_HILBERTQUADKEYFROMID
(id STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
IMMUTABLE
AS $$
    if (!ID) {
        throw new Error('NULL argument passed to UDF');
    }

    @@SF_LIBRARY_CONTENT@@

    return s2Lib.idToKey(ID);
$$;

CREATE OR REPLACE SECURE FUNCTION S2_HILBERTQUADKEYFROMID
(id BIGINT)
RETURNS STRING
IMMUTABLE
AS $$
    __S2_HILBERTQUADKEYFROMID(CAST(ID AS STRING))
$$;