----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE FUNCTION _S2_HILBERTQUADKEYFROMCELLID
(id STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
    @@SF_LIBRARY_CONTENT@@
    
    if (!ID) {
        throw new Error('NULL argument passed to UDF');
    }

    return s2Lib.idToKey(ID);
$$;

CREATE OR REPLACE SECURE FUNCTION S2_HILBERTQUADKEYFROMCELLID
(id BIGINT)
RETURNS STRING
AS $$
    _S2_HILBERTQUADKEYFROMCELLID(CAST(ID AS STRING))
$$;