----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE FUNCTION _PLACEKEY_FROMH3
(h3Index STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS $$
    @@SF_LIBRARY_CONTENT@@
    
    return placekeyLib.h3ToPlacekey(H3INDEX);
$$;

CREATE OR REPLACE SECURE FUNCTION PLACEKEY_FROMH3
(h3Index STRING)
RETURNS STRING
AS $$
    IFF(H3_ISVALID(H3INDEX),
      _PLACEKEY_FROMH3(H3INDEX),
      null)
$$;