--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__QUADINT_KRING_DISTANCES
(BIGINT, INT)
-- (origin, size)
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@';

CREATE OR REPLACE FUNCTION @@SCHEMA@@.QUADINT_KRING_DISTANCES
(BIGINT, INT)
-- (origin, size)
RETURNS SUPER
STABLE
AS $$
    SELECT json_parse(@@SCHEMA@@.__QUADINT_KRING_DISTANCES($1, $2))
$$ LANGUAGE sql;