--------------------------------
-- Copyright (C) 2021-2025 CARTO
--------------------------------

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_CENTERMEDIAN
(GEOMETRY)
-- (geom)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMTEXT(@@RS_SCHEMA@@.__CENTERMEDIAN(ST_ASGEOJSON($1)::VARCHAR(MAX), 100), 4326)
$$ LANGUAGE sql;
