--------------------------------
-- Copyright (C) 2021-2025 CARTO
--------------------------------

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_CENTROID
(GEOMETRY)
-- (geom)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMTEXT(@@RS_SCHEMA@@.__CENTROID(ST_ASGEOJSON($1)::VARCHAR(MAX)), 4326)
$$ LANGUAGE sql;
