--------------------------------
-- Copyright (C) 2021-2025 CARTO
--------------------------------

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_DESTINATION
(GEOMETRY, FLOAT8, FLOAT8)
-- (geom, distance, bearing)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMTEXT(@@RS_SCHEMA@@.__DESTINATION(ST_ASGEOJSON($1)::VARCHAR(MAX), $2, $3, 'kilometers'), 4326)
$$ LANGUAGE sql;


CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_DESTINATION
(GEOMETRY, FLOAT8, FLOAT8, VARCHAR(15))
-- (geom, distance, bearing, units)
RETURNS GEOMETRY
STABLE
AS $$
    SELECT ST_GEOMFROMTEXT(@@RS_SCHEMA@@.__DESTINATION(ST_ASGEOJSON($1)::VARCHAR(MAX), $2, $3, $4), 4326)
$$ LANGUAGE sql;
