# Production environment configuration for Redshift deployment

environment: prod

# AWS Configuration
aws:
  region: us-east-1
  account_id: "YOUR_AWS_ACCOUNT_ID"
  profile: production

# Lambda Configuration
lambda:
  prefix: "carto-at-prod"
  default_memory: 1024
  default_timeout: 120
  default_runtime: python3.11
  # Lambda execution role
  execution_role_name: "carto-at-lambda-execution-role-prod"
  # Enable X-Ray tracing
  enable_tracing: true
  # Reserved concurrent executions (null = unlimited)
  reserved_concurrency: null

# Redshift Configuration
redshift:
  # Cluster or workgroup identifier
  cluster_identifier: "prod-cluster"
  # Database name
  database: prod
  # Schema for Analytics Toolbox functions
  schema: carto
  # IAM role for Redshift to invoke Lambda
  lambda_invoke_role_name: "carto-at-redshift-invoke-role-prod"

# CDK Configuration
cdk:
  stack_name: "CartoATRedshiftProd"
  bootstrap_bucket_prefix: "carto-at-cdk"
  # Require manual approval for deployments
  require_approval: true
  tags:
    Environment: prod
    Project: CARTO Analytics Toolbox
    ManagedBy: CDK

# Deployment Options
deployment:
  # Deploy only modified functions (based on git diff)
  incremental: false  # Always deploy all in prod
  # Clean up old Lambda versions
  cleanup_old_versions: true
  # Maximum number of versions to keep
  max_versions: 5
  # Run tests after deployment
  run_tests: true
  # Rollback on test failure
  rollback_on_failure: true

# Monitoring
monitoring:
  # Enable CloudWatch alarms
  enable_alarms: true
  # SNS topic for alerts
  alert_topic_arn: "arn:aws:sns:us-east-1:ACCOUNT:carto-at-alerts"
  # Lambda error rate threshold (percentage)
  error_rate_threshold: 5
  # Lambda duration threshold (milliseconds)
  duration_threshold: 55000

# Testing
testing:
  # Test database connection string (use environment variable)
  connection_string_env: REDSHIFT_PROD_CONNECTION
  # Test user credentials (use environment variables)
  username_env: REDSHIFT_PROD_USER
  password_env: REDSHIFT_PROD_PASSWORD
