----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_DISTANCE
(index1 STRING, index2 STRING)
RETURNS BIGINT
IMMUTABLE
AS $$
    IFF(
	INDEX1 IS NOT NULL AND INDEX2 IS NOT NULL AND H3_GET_RESOLUTION(INDEX1) = H3_GET_RESOLUTION(INDEX2),
        CAST(H3_GRID_DISTANCE(INDEX1, INDEX2) AS BIGINT),
	NULL
    )
$$;
