----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_DISTANCE
(index1 STRING, index2 STRING)
RETURNS BIGINT
IMMUTABLE
AS $$
    IFF(
	@@SF_SCHEMA@@.H3_ISVALID(INDEX1) AND @@SF_SCHEMA@@.H3_ISVALID(INDEX2) AND H3_GET_RESOLUTION(INDEX1) = H3_GET_RESOLUTION(INDEX2),
        CAST(H3_GRID_DISTANCE(INDEX1, INDEX2) AS BIGINT),
	NULL
    )
$$;
