---------------------------------
-- Copyright (C) 2021-2024 CARTO
---------------------------------

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_FROMLONGLAT
(longitude DOUBLE, latitude DOUBLE, resolution INT)
RETURNS STRING
IMMUTABLE
AS $$
    IFF(LONGITUDE IS NOT NULL AND LATITUDE IS NOT NULL AND RESOLUTION >= 0 AND RESOLUTION <= 15,
	H3_LATLNG_TO_CELL_STRING(LATITUDE, LONGITUDE, RESOLUTION),
        NULL)
$$;
