----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_TOCHILDREN
(h3_int INT, resolution INT)
RETURNS ARRAY
IMMUTABLE
AS $$
    IFF(
	@@SF_SCHEMA@@.H3_ISVALID(h3_int) AND RESOLUTION >= H3_GET_RESOLUTION(h3_int),
	H3_CELL_TO_CHILDREN(h3_int, RESOLUTION),
	[]
    )
$$;

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_TOCHILDREN
(h3_hex VARCHAR, resolution INT)
RETURNS ARRAY
IMMUTABLE
AS $$
    IFF(
	@@SF_SCHEMA@@.H3_ISVALID(h3_hex) AND RESOLUTION >= H3_GET_RESOLUTION(h3_hex),
	H3_CELL_TO_CHILDREN_STRING(h3_hex, RESOLUTION),
	[]
    )
$$;
