----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_TOCHILDREN
(index INT, resolution INT)
RETURNS ARRAY
IMMUTABLE
AS $$
    IFF(
	@@SF_SCHEMA@@.H3_ISVALID(INDEX) AND RESOLUTION >= H3_GET_RESOLUTION(INDEX),
	H3_CELL_TO_CHILDREN(INDEX, RESOLUTION),
	[]
    )
$$;

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.H3_TOCHILDREN
(index VARCHAR, resolution INT)
RETURNS ARRAY
IMMUTABLE
AS $$
    IFF(
	@@SF_SCHEMA@@.H3_ISVALID(INDEX) AND RESOLUTION >= H3_GET_RESOLUTION(INDEX),
	H3_CELL_TO_CHILDREN_STRING(INDEX, RESOLUTION),
	[]
    )
$$;
