--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__QUADBIN_POLYFILL
(VARCHAR(MAX), INT)
-- (geojson, resolution)
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@'
MAX_BATCH_ROWS @@MAX_BATCH_ROWS@@;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.QUADBIN_POLYFILL
(GEOMETRY, INT)
-- (geo, resolution)
RETURNS SUPER
STABLE
AS $$
    SELECT CASE ST_SRID($1)
        WHEN 0 THEN JSON_PARSE(@@SCHEMA@@.__QUADBIN_POLYFILL(ST_ASGEOJSON(ST_SETSRID($1, 4326))::VARCHAR(MAX), $2))
        ELSE JSON_PARSE(@@SCHEMA@@.__QUADBIN_POLYFILL(ST_ASGEOJSON(ST_TRANSFORM($1, 4326))::VARCHAR(MAX), $2))
    END
$$ LANGUAGE sql;
