----------------------------
-- Copyright (C) 2025 CARTO
----------------------------

-- Internal function: Uses VARCHAR for FLOAT8 to preserve precision
CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__DESTINATION_INTERNAL
(VARCHAR(MAX), VARCHAR(MAX), VARCHAR(MAX), VARCHAR(15))
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@'
MAX_BATCH_ROWS @@MAX_BATCH_ROWS@@;

-- Private wrapper: Converts FLOAT8 to VARCHAR
CREATE OR REPLACE FUNCTION @@SCHEMA@@.__DESTINATION
(VARCHAR(MAX), FLOAT8, FLOAT8, VARCHAR(15))
RETURNS VARCHAR(MAX)
STABLE
AS $$
    SELECT @@SCHEMA@@.__DESTINATION_INTERNAL(
        $1,
        CAST($2 AS VARCHAR(MAX)),
        CAST($3 AS VARCHAR(MAX)),
        $4
    )
$$ LANGUAGE sql;
