# Makefile for Redshift Python library
# NOTE: This directory will be deprecated and ported to gateway/functions
# as Lambda-based external functions replace Python 2.7 UDFs

ROOT_DIR := $(shell dirname $(abspath $(lastword $(MAKEFILE_LIST))))

.SILENT:

.PHONY: help

help:
	echo "Python 2.7 library system has been removed."
	echo "These functions will be migrated to gateway/ as Lambda-based external functions."
	echo "See gateway/ directory and claude_instructions.md for the new architecture."
