----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_VORONOILINES
(GEOMETRY, SUPER)
-- (points)
RETURNS VARCHAR(MAX)
STABLE
AS $$
    SELECT @@RS_SCHEMA@@.__VORONOIGENERIC(ST_ASGEOJSON($1)::VARCHAR(MAX), JSON_SERIALIZE($2)::VARCHAR(MAX), 'lines')
$$ LANGUAGE SQL;


CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_VORONOILINES
(GEOMETRY)
-- (points)
RETURNS VARCHAR(MAX)
STABLE
AS $$
    SELECT @@RS_SCHEMA@@.__VORONOIGENERIC(ST_ASGEOJSON($1)::VARCHAR(MAX), NULL, 'lines')
$$ LANGUAGE SQL;
