--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__S2_TOPARENT(
    id INT8,
    resolution INT4
)
RETURNS INT8
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@'
MAX_BATCH_ROWS @@MAX_BATCH_ROWS@@;

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__S2_TOPARENT(
    id INT8
)
RETURNS INT8
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@'
MAX_BATCH_ROWS @@MAX_BATCH_ROWS@@;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.S2_TOPARENT(id INT8, resolution INT4)
RETURNS INT8
STABLE
AS $$
    SELECT @@SCHEMA@@.__S2_TOPARENT($1, $2)
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.S2_TOPARENT(id INT8)
RETURNS INT8
STABLE
AS $$
    SELECT @@SCHEMA@@.__S2_TOPARENT($1)
$$ LANGUAGE sql;
