--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__QUADBIN_KRING_DISTANCES
(BIGINT, INT)
-- (origin, size)
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@'
MAX_BATCH_ROWS @@MAX_BATCH_ROWS@@;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.QUADBIN_KRING_DISTANCES
(BIGINT, INT)
-- (origin, size)
RETURNS SUPER
STABLE
AS $$
    SELECT JSON_PARSE(@@SCHEMA@@.__QUADBIN_KRING_DISTANCES($1, $2))
$$ LANGUAGE sql;
