-----------------------------------------------------------------------
--
-- Copyright (C) 2021 CARTO
--
-----------------------------------------------------------------------
-- 
-- CREATE OR REPLACE FUNCTION `@@BQ_PROJECTID@@.@@BQ_DATASET_PLACEKEY@@.H3_FROMPLACEKEY`(placekey STRING)
--     RETURNS INT64
--     DETERMINISTIC
--     LANGUAGE js
--     OPTIONS (library=["@@PLACEKEY_BQ_LIBRARY@@"])
-- AS """
--     return 'Ox' || placekeyToH3(placekey);
-- """;
