--------------------------------
-- Copyright (C) 2021-2024 CARTO
--------------------------------

CREATE OR REPLACE FUNCTION @@SF_SCHEMA@@._ST_GENERATEPOINTS
(geojson STRING, npoints DOUBLE)
RETURNS ARRAY
LANGUAGE JAVASCRIPT
IMMUTABLE
AS $$
    @@SF_LIBRARY_RANDOM@@

    return randomLib.generateRandomPointsInPolygon(JSON.parse(GEOJSON), NPOINTS);
$$;

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.ST_GENERATEPOINTS
(geog GEOGRAPHY, npoints INT)
RETURNS ARRAY
IMMUTABLE
AS $$
    @@SF_SCHEMA@@._ST_GENERATEPOINTS(
        ST_ASGEOJSON(GEOG)::STRING,
        NPOINTS
    )
$$;
