--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__QUADBIN_BBOX
(BIGINT)
-- (quadbin)
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@';

CREATE OR REPLACE FUNCTION @@SCHEMA@@.QUADBIN_BBOX
(BIGINT)
-- (quadbin)
RETURNS SUPER
STABLE
AS $$
    SELECT JSON_PARSE(@@SCHEMA@@.__QUADBIN_BBOX($1))
$$ LANGUAGE sql;
