name: Deploy Staging SF

on:
  pull_request_review:
    types: [submitted]

env:
  ENABLED_SF: 1
  GCLOUD_VERSION: 'latest'
  SNOWSQL_VERSION: 1.2.13
  SNOWSQL: ~/snowflake/snowsql
  SNOWSQL_DEST: ~/snowflake
  SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
  SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
  SF_DATABASEID: SFCARTOST
  SF_SHARE_ENABLED: 1
  SF_SHARE_PUBLIC: SFCARTOST
  SF_SCHEMA_H3: H3
  SF_SCHEMA_PLACEKEY: PLACEKEY
  SF_SCHEMA_QUADKEY: QUADKEY
  SF_SCHEMA_S2: S2

jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install snowsql
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
      - name: Deploy to staging
        run: make deploy
