--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__S2_TOCHILDREN(
    id INT8,
    resolution INT4
)
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@';

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__S2_TOCHILDREN(
    id INT8
)
RETURNS VARCHAR(MAX)
STABLE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@';

CREATE OR REPLACE FUNCTION @@SCHEMA@@.S2_TOCHILDREN(id INT8, resolution INT4)
RETURNS SUPER
STABLE
AS $$
    SELECT json_parse(@@SCHEMA@@.__S2_TOCHILDREN($1, $2))
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.S2_TOCHILDREN(id INT8)
RETURNS SUPER
STABLE
AS $$
    SELECT json_parse(@@SCHEMA@@.__S2_TOCHILDREN($1))
$$ LANGUAGE sql;
