----------------------------
-- Copyright (C) 2021 CARTO
----------------------------

CREATE OR REPLACE FUNCTION @@SF_SCHEMA@@._PLACEKEY_FROMH3
(h3Index STRING)
RETURNS STRING
LANGUAGE JAVASCRIPT
IMMUTABLE
AS $$
    @@SF_LIBRARY_PLACEKEY@@

    return placekeyLib.h3ToPlacekey(H3INDEX);
$$;

CREATE OR REPLACE SECURE FUNCTION @@SF_SCHEMA@@.PLACEKEY_FROMH3
(h3Index STRING)
RETURNS STRING
IMMUTABLE
AS $$
    IFF(@@SF_SCHEMA@@.H3_ISVALID(H3INDEX),
      @@SF_SCHEMA@@._PLACEKEY_FROMH3(H3INDEX),
      null)
$$;