--------------------------------
-- Copyright (C) 2021-2025 CARTO
--------------------------------

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_CLUSTERKMEANS
(GEOMETRY)
-- (geom)
RETURNS SUPER
STABLE
AS $$
    SELECT json_parse(@@RS_SCHEMA@@.__CLUSTERKMEANS(ST_ASGEOJSON($1), SQRT(ST_NPoints($1)/2)::INT))
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION @@RS_SCHEMA@@.ST_CLUSTERKMEANS
(GEOMETRY, INT)
-- (geom, numberofClusters)
RETURNS SUPER
STABLE
AS $$
    SELECT json_parse(@@RS_SCHEMA@@.__CLUSTERKMEANS(ST_ASGEOJSON($1), $2))
$$ LANGUAGE sql;
