name: Bigquery dedicated env

on:
  pull_request:
    types: [closed, unlabeled, labeled, synchronize]

env:
  NODE_VERSION: 14

jobs:

  dedicated:
    if: github.event.label.name == 'dedicated_bigquery' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'dedicated_bigquery'))
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_PREFIX: dedicated_${{ github.event.pull_request.number }}_
      BQ_PROJECT: ${{ secrets.BQ_PROJECT_DEDICATED }}
      BQ_REGION: ${{ secrets.BQ_REGION_DEDICATED }}
      BQ_BUCKET: ${{ secrets.BQ_BUCKET_DEDICATED }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTO_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Run deploy
        id: deploy
        if: contains(github.event.pull_request.labels.*.name, 'dedicated_bigquery')
        run: |
          cd clouds/bigquery
          make deploy
      - name: Run remove
        id: remove
        if: github.event.action == 'unlabeled' || github.event.action == 'closed'
        run: |
          cd clouds/bigquery
          make remove
      - name: Comment deploy PR
        if: steps.deploy.outcome == 'success' && github.event.action == 'labeled'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Dedicated ${{ env.BQ_PREFIX }}carto environment deployed in Bigquery project ${{ env.BQ_PROJECT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment remove PR
        if: steps.remove.outcome == 'success' && (github.event.action == 'unlabeled' || github.event.action == 'closed')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Dedicated environment removed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
