name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request_target:
    types: [labeled]

env:
  NODE_VERSION: 14

jobs:

  lint-bq:
    if: |
      ( github.event_name == 'push' ) ||
      ( github.event_name == 'pull_request_target' && github.event.label.name == 'run_ci' )
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Check linter
        run: make lint CLOUD=bigquery

  test-unit-bq:
    needs: lint-bq
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run unit tests
        run: make test-unit CLOUD=bigquery

  test-integration-bq:
    needs: lint-bq
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: us
      BQ_PROJECT: bqcartoci
      BQ_BUCKET: gs://bqcartoci/
      BQ_DATASET_PREFIX: ci_${{ github.sha }}_${{ github.run_id }}_
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTOCI_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Run integration tests
        run: make test-integration-full CLOUD=bigquery
