name: Installation package

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud warehouse (redshift)'
        required: true
        default: ''

jobs:

  create-sf:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: ${{ github.event.inputs.cloud == 'snowflake'}}
    env:
      PACKAGE_TYPE: CORE
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create installation package
        run: ./common/snowflake/release_installation_package.sh
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: carto-analytics-toolbox-core-snowflake
          path: dist/modules.sql

  create-rs:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: ${{ github.event.inputs.cloud == 'redshift'}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup virtualenv
        run: pip install virtualenv
      - name: Create installation package
        run: ./common/redshift/release_installation_package.sh
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: carto-analytics-toolbox-core-redshift
          path: dist/*