name: Delete Staging

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud warehouse (bigquery, all)'
        required: true
        default: 'all'
      pr_number:
        description: PR number
        required: true

jobs:

  delete-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: |
      ( github.event_name == 'pull_request' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["bigquery", "all"]'), github.event.inputs.cloud) )
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_PROJECT: bqcartost-core-${{ github.event.inputs.pr_number || github.event.pull_request.number }}
    steps:
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTOCUSTOMST_DEPLOY_CLOUD_EXTENSIONS_SA }}
          project_id: ${{ env.BQ_PROJECT }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Delete project
        shell: bash
        run: gcloud projects delete ${{ env.BQ_PROJECT }} --quiet
      - name: Comment PR
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo: { owner, repo }  } = context;
            const issue_number = ${{ github.event.inputs.pr_number || github.event.pull_request.number }};
            github.issues.createComment({ issue_number, owner, repo, body: 'Project `${{ env.BQ_PROJECT }}` deleted! 🔥' });
