name: Delete Staging

on:
  pull_request:
    types: [closed]

jobs:

  delete-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_PROJECT: bqcartost-core-${{ github.event.pull_request.number }}
    steps:
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
            service_account_key: ${{ secrets.BQCARTOCUSTOMST_DEPLOY_CLOUD_EXTENSIONS_SA }}
      - name: Delete project
        shell: bash
        run: gcloud projects delete ${{ env.BQ_PROJECT }} --quiet 
      - name: Comment PR
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo: { owner, repo }  } = context;
            const issue_number = ${{ github.event.pull_request.number }};
            github.issues.createComment({ issue_number, owner, repo, body: 'Project `${{ env.BQ_PROJECT }}` deleted! 🔥' });