name: Dedicated env - Deploy
on:
  pull_request:
    types:
      - labeled

jobs:
  deploy-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: github.event.label.name == 'dedicated_bigquery'
    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v2
      #   with:
      #     submodules: recursive
      # - name: Setup cache
      #   id: cache-system-libraries
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ env.EM_CACHE_FOLDER }}
      #     key: ${{ runner.os }}_${{ env.EM_VERSION }}
      # - name: Setup emscripten
      #   uses: mymindstorm/setup-emsdk@master
      #   with:
      #     version: ${{ env.EM_VERSION }}
      #     actions-cache-folder: ${{ env.EM_CACHE_FOLDER }}
      # - name: Setup gcloud
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #       version: 290.0.1
      #       project_id: carto-${{ github.event.inputs.price_plan }}
      #       service_account_key: ${{ secrets.BQCARTO_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
      #       export_default_credentials: true
      - name: Check label
        # env:
        #   PACKAGE_NAME: carto-${{ env.INPUT_PRICE_PLAN }}
        #   PACKAGE_TYPE: ${{ env.PACKAGE_TYPE || 'advanced' }}
        #   PACKAGE_BUCKET: gs://spatialextension_${{ env.INPUT_PRICE_PLAN }}/installation_packages
        #   BQ_MAX_ROWS_TILER: ${{ env.MAX_ROWS_TILER }}
        shell: bash
        run: |
          echo "Dedicated for Bigquery"

  deploy-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: github.event.label.name == 'dedicated_snowflake'
    steps:
      - name: Check label
        shell: bash
        run: |
          echo "Dedicated for Snowflake"