name: Deploy Production

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud warehouse (bigquery, snowflake, redshift, postgres, all)'
        required: true
        default: 'all'
      force_deploy:
        description: 'Force deployment of all modules'
        required: true
        default: 'false'

env:
  INPUT_FORCE_DEPLOY: ${{ github.event.inputs.force_deploy }}

jobs:

  deploy-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: |
      ( github.event_name == 'push' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["bigquery", "all"]'), github.event.inputs.cloud) )
    strategy:
      matrix:
        include:
          - region: us
            project: carto-os
            bucket: gs://spatialextension_os/
            permissions: '[{"specialGroup":"allAuthenticatedUsers","role":"READER"}]'
          - region: us
            project: carto-st
            bucket: gs://spatialextension_st/
            group: spatialextension_users_st@cartodb.com
          - region: us
            project: carto-sm
            bucket: gs://spatialextension_sm/
            group: spatialextension_users_sm@cartodb.com
          - region: us
            project: carto-me
            bucket: gs://spatialextension_me/
            group: spatialextension_users_me@cartodb.com
          - region: us
            project: carto-la
            bucket: gs://spatialextension_la/
            group: spatialextension_users_la@cartodb.com
          - region: us
            project: carto-un
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: eu
            project: carto-os-eu
            bucket: gs://spatialextension_os/
            permissions: '[{"specialGroup":"allAuthenticatedUsers","role":"READER"}]'
          - region: eu
            project: carto-st-eu
            bucket: gs://spatialextension_st/
            group: spatialextension_users_st@cartodb.com
          - region: eu
            project: carto-sm-eu
            bucket: gs://spatialextension_sm/
            group: spatialextension_users_sm@cartodb.com
          - region: eu
            project: carto-me-eu
            bucket: gs://spatialextension_me/
            group: spatialextension_users_me@cartodb.com
          - region: eu
            project: carto-la-eu
            bucket: gs://spatialextension_la/
            group: spatialextension_users_la@cartodb.com
          - region: eu
            project: carto-un-eu
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-northeast1
            project: carto-un-as-ne1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: australia-southeast1
            project: carto-un-au-se1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: northamerica-northeast1
            project: carto-un-na-ne1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-southeast1
            project: carto-un-as-se1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-central1
            project: carto-un-us-ce1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-west1
            project: carto-un-us-we1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-west2
            project: carto-un-us-we2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-west3
            project: carto-un-us-we3
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-west4
            project: carto-un-us-we4
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-east1
            project: carto-un-us-ea1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: us-east4
            project: carto-un-us-ea4
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: southamerica-east1
            project: carto-un-sa-ea1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: southamerica-west1
            project: carto-un-sa-we1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: northamerica-northeast2
            project: carto-un-na-ne2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-south1
            project: carto-un-as-so1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-south2
            project: carto-un-as-so2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-east1
            project: carto-un-as-ea1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-east2
            project: carto-un-as-ea2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-northeast2
            project: carto-un-as-ne2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-northeast3
            project: carto-un-as-ne3
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: asia-southeast2
            project: carto-un-as-se2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: australia-southeast2
            project: carto-un-au-se2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-west1
            project: carto-un-eu-we1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-west2
            project: carto-un-eu-we2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-west3
            project: carto-un-eu-we3
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-west4
            project: carto-un-eu-we4
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-west6
            project: carto-un-eu-we6
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-north1
            project: carto-un-eu-no1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: europe-central2
            project: carto-un-eu-ce2
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com

    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: ${{ matrix.region }}
      BQ_PROJECT: ${{ matrix.project }}
      BQ_BUCKET: ${{ matrix.bucket }}
      BQ_PERMISSIONS: ${{ matrix.permissions }}
      BQ_PERMISSIONS_GROUP: ${{ matrix.group }}
      BQ_PERMISSIONS_ROLE_NAME: spatialextensionUser
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTO_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Deploy to production
        run: make deploy CLOUD=bigquery

  deploy-sf:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: false
    env:
      SNOWSQL_VERSION: 1.2.13
      SNOWSQL_BIN: ~/snowflake/snowsql
      SNOWSQL_DEST: ~/snowflake
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USER: ${{ secrets.SF_USERNAME }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SF_DATABASE: CARTO_OS
      SF_SHARE_ENABLED: 1
      SF_SHARES: carto_os_temp
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup snowsql
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
      - name: Deploy to production
        run: make deploy CLOUD=snowflake
