name: Dedicated env - Deploy
on:
  pull_request:
    types:
      - labeled

jobs:
  deploy-bq:
    if: github.event.label.name == 'dedicated_bigquery'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: 'us'
      BQ_PROJECT: 'carto-dev-data'
      BQ_DATASET_PREFIX: dedicated_${{ git rev-parse --short HEAD }}_${{ github.event.number }}_
      BQ_BUCKET: gs://bqcartodev/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTO_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Run deploy
        run: |
          cd clouds/bigquery
          make deploy

  deploy-sf:
    if: github.event.label.name == 'dedicated_snowflake'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check label
        shell: bash
        run: |
          echo "dedicated_${{ env.BQ_DATASET_PREFIX }}"