name: Deploy Production

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud warehouse (bigquery, snowflake, redshift, all)'
        required: true
        default: 'all'
      force_deploy:
        description: 'Force deployment of all modules'
        required: true
        default: 'false'

env:
  INPUT_FORCE_DEPLOY: ${{ github.event.inputs.force_deploy }}

jobs:

  deploy-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: |
      ( github.event_name == 'push' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["bigquery", "all"]'), github.event.inputs.cloud) )
    strategy:
      matrix:
        include:
          - region: us
            project: carto-os
            bucket: gs://spatialextension_os/
            permissions: '[{"specialGroup":"allAuthenticatedUsers","role":"READER"}]'
          - region: us
            project: carto-st
            bucket: gs://spatialextension_st/
            group: spatialextension_users_st@cartodb.com
          - region: us
            project: carto-sm
            bucket: gs://spatialextension_sm/
            group: spatialextension_users_sm@cartodb.com
          - region: us
            project: carto-me
            bucket: gs://spatialextension_me/
            group: spatialextension_users_me@cartodb.com
          - region: us
            project: carto-la
            bucket: gs://spatialextension_la/
            group: spatialextension_users_la@cartodb.com
          - region: us
            project: carto-un
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: eu
            project: carto-os-eu
            bucket: gs://spatialextension_os/
            permissions: '[{"specialGroup":"allAuthenticatedUsers","role":"READER"}]'
          - region: eu
            project: carto-st-eu
            bucket: gs://spatialextension_st/
            group: spatialextension_users_st@cartodb.com
          - region: eu
            project: carto-sm-eu
            bucket: gs://spatialextension_sm/
            group: spatialextension_users_sm@cartodb.com
          - region: eu
            project: carto-me-eu
            bucket: gs://spatialextension_me/
            group: spatialextension_users_me@cartodb.com
          - region: eu
            project: carto-la-eu
            bucket: gs://spatialextension_la/
            group: spatialextension_users_la@cartodb.com
          - region: eu
            project: carto-un-eu
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: as
            project: carto-un-as
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: au
            project: carto-un-au
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
          - region: northamerica-northeast1
            project: carto-un-na-ne1
            bucket: gs://spatialextension_un/
            group: spatialextension_users_un@cartodb.com
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: ${{ matrix.region }}
      BQ_PROJECT: ${{ matrix.project }}
      BQ_BUCKET: ${{ matrix.bucket }}
      BQ_PERMISSIONS: ${{ matrix.permissions }}
      BQ_PERMISSIONS_GROUP: ${{ matrix.group }}
      BQ_PERMISSIONS_ROLE_NAME: spatialextensionUser
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTO_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Deploy to production
        run: make deploy CLOUD=bigquery

  deploy-sf:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: |
      ( github.event_name == 'push' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["snowflake", "all"]'), github.event.inputs.cloud) )
    env:
      SNOWSQL_VERSION: 1.2.13
      SNOWSQL: ~/snowflake/snowsql
      SNOWSQL_DEST: ~/snowflake
      SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
      SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
      SF_DATABASE: CARTO_OS
      SF_SHARE_ENABLED: 1
      SF_SHARES: carto_os
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup snowsql
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
      - name: Deploy to production
        run: make deploy CLOUD=snowflake

  deploy-rs:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: |
      ( github.event_name == 'push' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["redshift", "all"]'), github.event.inputs.cloud) )
    env:
      RS_REGION: us-east-2
      RS_HOST: redshift-cluster-1.c2gsqdockj5a.us-east-2.redshift.amazonaws.com
      RS_CLUSTER_ID: redshift-cluster-1
      RS_DATABASE: rscarto
      RS_USER: ${{ secrets.RS_USER }}
      RS_PASSWORD: ${{ secrets.RS_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.RS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.RS_AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: s3://rscarto/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Setup virtualenv
        run: pip install virtualenv
      - name: Deploy to production
        run: make deploy CLOUD=redshift
