name: Deploy Staging

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud warehouse (bigquery, all)'
        required: true
        default: 'all'
      pr_number:
        description: PR number
        required: true

jobs:

  deploy-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    if: |
      ( github.event_name == 'pull_request_review' && github.event.review.state == 'approved' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["bigquery", "all"]'), github.event.inputs.cloud) )
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: us
      BQ_PROJECT: bqcartost-core-${{ github.event.inputs.pr_number || github.event.pull_request.number }}
      BQ_BUCKET: gs://carto-ext-ci-public-bqcartost-core-${{ github.event.inputs.pr_number || github.event.pull_request.number }}/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTOCUSTOMST_DEPLOY_CLOUD_EXTENSIONS_SA }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Create temporary staging environment
        shell: bash
        run: ./common/bigquery/create_staging_env.sh
      - name: Deploy to staging
        run: make deploy CLOUD=bigquery
      - name: Comment PR
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo: { owner, repo }  } = context;
            const issue_number = ${{ github.event.inputs.pr_number || github.event.pull_request.number }};
            github.issues.createComment({ issue_number, owner, repo, body: 'Deployed in project `${{ env.BQ_PROJECT }}`: https://console.cloud.google.com/bigquery?project=${{env.BQ_PROJECT}}' });
