name: Deploy Staging BQ

on:
  pull_request_review:
    types: [submitted]

env:
  ENABLED_BQ: 1
  GCLOUD_VERSION: 'latest'
  BQ_REGION: us
  BQ_PROJECTID: bqcartost
  BQ_BUCKET_PUBLIC: gs://bqcartost-public/
  BQ_DATASET_SKEL: skel
  BQ_DATASET_H3: h3
  BQ_DATASET_PLACEKEY: placekey
  BQ_DATASET_QUADKEY: quadkey
  BQ_DATASET_S2: s2
  BQ_DATASET_TRANSFORMATION: transformation

jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECTID }}
            service_account_key: ${{ secrets.BQCARTOST_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
            export_default_credentials: true
      - name: Deploy to staging
        run: make deploy
