name: Staging

on:
  pull_request_review:
    types: [submitted]

jobs:

  deploy-bq:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      ENABLED_BQ: 1
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: us
      BQ_PROJECTID: bqcartost
      BQ_BUCKET_PUBLIC: gs://bqcartost-public/
      BQ_DATASET_SKEL: skel
      BQ_DATASET_H3: h3
      BQ_DATASET_PLACEKEY: placekey
      BQ_DATASET_QUADKEY: quadkey
      BQ_DATASET_S2: s2
      BQ_DATASET_TRANSFORMATION: transformation
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECTID }}
            service_account_key: ${{ secrets.BQCARTOST_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
            export_default_credentials: true
      - name: Deploy to staging
        run: make deploy

  deploy-sf:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      ENABLED_SF: 1
      SNOWSQL_VERSION: 1.2.13
      SNOWSQL: ~/snowflake/snowsql
      SNOWSQL_DEST: ~/snowflake
      SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
      SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
      SF_DATABASEID: SFCARTOST
      SF_SHARE_ENABLED: 1
      SF_SHARE_PUBLIC: SFCARTOST
      SF_SCHEMA_SKEL: SKEL
      SF_SCHEMA_H3: H3
      SF_SCHEMA_PLACEKEY: PLACEKEY
      SF_SCHEMA_QUADKEY: QUADKEY
      SF_SCHEMA_S2: S2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Install snowsql
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
      - name: Deploy to staging
        run: make deploy
