name: Dedicated env - Deploy
on:
  pull_request:
    types: [closed, unlabeled, labeled]

env:
  NODE_VERSION: 14

jobs:
  dedicated-bq:
    if: github.event.label.name == 'dedicated_bigquery'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: us
      BQ_PROJECT: cartodb-gcp-backend-data-team
      BQ_PREFIX: dedicated_${{ github.event.pull_request.number }}_
      BQ_BUCKET: gs://bqcartodev/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.BQCARTO_DEPLOY_CLOUD_DEDICATED_SA_BASE64 }}
          project_id: ${{ env.BQ_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECT }}
      - name: Run deploy
        if: github.event.action == 'labeled'
        run: |
          cd clouds/bigquery
          make deploy
      - name: Run release
        if: github.event.action != 'labeled'
        run: |
          cd clouds/bigquery
          make remove

  dedicated-sf:
    if: github.event.label.name == 'dedicated_snowflake'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      SF_PREFIX: dedicated_${{ github.event.pull_request.number }}_
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT_DEDICATED }}
      SF_DATABASE: ${{ secrets.SF_DATABASE_DEDICATED }}
      SF_USER: ${{ secrets.SF_USER_DEDICATED }}
      SF_PASSWORD: ${{ secrets.SF_PASSWORD_DEDICATED }}
      SF_ROLE: ${{ secrets.SF_ROLE_DEDICATED }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run deploy
        if: github.event.action == 'labeled'
        run: |
          cd clouds/snowflake
          make deploy
      - name: Run release
        if: github.event.action != 'labeled'
        run: |
          cd clouds/snowflake
          make remove