name: Oracle dedicated env

on:
  pull_request:
    types: [closed, unlabeled, labeled, synchronize]

env:
  NODE_VERSION: 20.19
  PYTHON3_VERSION: 3.10.13
  VIRTUALENV_VERSION: 20.15.1

jobs:

  dedicated:
    if: |
      github.event.label.name == 'dedicated_oracle' ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'dedicated_oracle')) ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'dedicated_oracle'))
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Auth google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CARTO_AT_GH_ACTIONS_SERVICE_ACCOUNT_KEY }}
      - name: Retrieve secrets (CD)
        id: get-gcp-secrets-cd
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            ORA_DB_CREDENTIALS:projects/carto-terraform-ci-cd/secrets/carto-golden-dataset-credentials
      - name: Set ORA_PREFIX for releases
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          echo "ORA_PREFIX=DEDICATED_RELEASE_${{ github.event.pull_request.number }}_" >> $GITHUB_ENV
      - name: Set ORA_PREFIX for hotfixes
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          echo "ORA_PREFIX=DEDICATED_HOTFIX_${{ github.event.pull_request.number }}_" >> $GITHUB_ENV
      - name: Set ORA_PREFIX for regular deploys
        if: |
          !(startsWith(github.event.pull_request.head.ref, 'hotfix/')) &&
          !(startsWith(github.event.pull_request.head.ref, 'release/'))
        run: echo "ORA_PREFIX=DEDICATED_${{ github.event.pull_request.number }}_" >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup yarn
        run: npm install -g yarn
      - name: Setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON3_VERSION }}
      - name: Setup virtualenv
        run: pip install virtualenv==${{ env.VIRTUALENV_VERSION }}
      - name: Run deploy
        id: deploy
        if: github.event.action == 'synchronize' || github.event.action == 'labeled'
        env:
          ORA_USER: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.user }}
          ORA_PASSWORD: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.password }}
          ORA_WALLET_ZIP: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.walletZip }}
          ORA_WALLET_PASSWORD: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.walletPassword }}
          ORA_CONNECTION_STRING: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.connectionString }}
        run: |
          cd clouds/oracle
          make deploy
      - name: Run remove
        id: remove
        if: github.event.action == 'unlabeled' || github.event.action == 'closed'
        env:
          ORA_USER: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.user }}
          ORA_PASSWORD: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.password }}
          ORA_WALLET_ZIP: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.walletZip }}
          ORA_WALLET_PASSWORD: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.walletPassword }}
          ORA_CONNECTION_STRING: ${{ fromJSON(steps.get-gcp-secrets-cd.outputs.ORA_DB_CREDENTIALS).databases.oracle.config.credentials.connectionString }}
        run: |
          cd clouds/oracle
          make remove drop-schema=1
      - name: Comment deploy PR
        if: steps.deploy.outcome == 'success' && github.event.action == 'labeled'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Dedicated ${{ env.ORA_PREFIX }}CARTO schema deployed in Oracle Autonomous Database
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment remove PR
        if: steps.remove.outcome == 'success' && (github.event.action == 'unlabeled' || github.event.action == 'closed')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Dedicated environment removed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
