name: Release Production

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud (snowflake)'
        required: true
        default: ''

env:
  GCLOUD_VERSION: 290.0.1

jobs:

  release-sf:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    if: ${{ github.event.inputs.cloud == 'snowflake'}}
    env:
      PACKAGE_TYPE: CORE
      PACKAGE_BUCKET: gs://carto-analytics-toolbox/core/snowflake
      MAKE_RELEASE: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Check diff
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: '**/*.+(js|sql)'
          FILES: 'Makefile'
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ secrets.GCLOUD_PRODUCTION_PROJECT }}
            service_account_key: ${{ secrets.GCLOUD_PRODUCTION_RELEASE_SA }}
            export_default_credentials: true
      - name: Release installation package
        run: ./common/snowflake/release_installation_package.sh
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: carto-analytics-toolbox-core-snowflake
          path: dist/*
