name: Release Production

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud warehouse (bigquery, all)'
        required: true
        default: 'all'

env:
  GCLOUD_VERSION: 290.0.1

jobs:

  release-bq:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    if: |
      ( github.event_name == 'push' ) ||
      ( github.event_name == 'workflow_dispatch' && contains(fromJson('["bigquery", "all"]'), github.event.inputs.cloud) )
    env:
      PACKAGE_NAME: carto-analytics-toolbox-core-bigquery
      PACKAGE_BUCKET: gs://carto-analytics-toolbox-core/bigquery
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCLOUD_PRODUCTION_RELEASE_SA }}
          project_id: ${{ env.GCLOUD_PRODUCTION_PROJECT }}
          create_credentials_file: true
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ secrets.GCLOUD_PRODUCTION_PROJECT }}
      - name: Create installation package
        run: ./common/bigquery/create_installation_package.sh
      - name: Upload the package to the bucket
        run: |
          gsutil -h "Content-Type:application/zip" cp dist/*.zip ${{ env.PACKAGE_BUCKET }}/
          gsutil -h "Content-Type:application/zip" cp dist/*.zip ${{ env.PACKAGE_BUCKET }}/${{ env.PACKAGE_NAME }}-latest.zip
