name: Dedicated env - Release
on:
  pull_request:
    types:
      - [closed, unlabeled]

jobs:
  deploy-bq:
    if: github.event.label.name == 'dedicated_bigquery'
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    env:
      GCLOUD_VERSION: 290.0.1
      BQ_REGION: us
      BQ_PROJECT: cartodb-gcp-backend-data-team
      BQ_PREFIX: dedicated_${{ github.event.pull_request.number }}_
      BQ_BUCKET: gs://bqcartodev/
    steps:
      - name: Check label
        shell: bash
        run: |
          echo "Release BQ"

  deploy-sf:
    if: github.event.label.name == 'dedicated_snowflake'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Check label
        shell: bash
        run: |
          echo "Release SF"