name: Test Integration BQ

on:
  # For internal contributors we use `push` event and CI runs automatically
  push:
  # `pull_request` event is **intentionally** excluded because we need to check
  # the code from external contributors before running it. Once verified
  # CARTO member should label the pull request with `run_ci` label
  # this will trigger one execution of ci using the external code.
  # to run it again we need to remove then add the `run_ci` label
  pull_request_target:
    types: [labeled]

env:
  ENABLED_BQ: 1
  NODE_VERSION: 14
  GCLOUD_VERSION: 290.0.1
  BQ_PROJECTID: bqcartoci
  BQ_BUCKET_PUBLIC: gs://bqcartoci/
  BQ_DATASET_PREFIX: ci_${{ github.sha }}_${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check if fork pull request can run CI
        if: github.event_name == 'pull_request_target'
        run: |
           if [[ "${{ github.event.action == 'labeled' && github.event.label.name == 'run_ci' }}" == "true" ]]; then
             echo "Fork pull request was labeled: ${{github.event.label.name}} by ${{ github.event.sender.login }}"
           else
             echo "Fork pull request needs to be verified by CARTO member then labeled with run_ci"
             exit 1
           fi
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
            version: ${{ env.GCLOUD_VERSION }}
            project_id: ${{ env.BQ_PROJECTID }}
            service_account_key: ${{ secrets.BQCARTOCI_DEPLOY_CLOUD_EXTENSIONS_SA_BASE64 }}
            export_default_credentials: true
      - name: Get environment
        run: |
          source tools/dev_environment.sh.sample
          env >> $GITHUB_ENV
      - name: Build
        run: make
      - name: Run integration tests
        run: make check-integration
