name: Test Integration SF

on:
  # For internal contributors we use `push` event and CI runs automatically
  push:
  # `pull_request` event is **intentionally** excluded because we need to check
  # the code from external contributors before running it. Once verified
  # CARTO member should label the pull request with `run_ci` label
  # this will trigger one execution of ci using the external code.
  # to run it again we need to remove then add the `run_ci` label
  pull_request_target:
    types: [labeled]

env:
  ENABLED_SF: 1
  NODE_VERSION: 14
  GCLOUD_VERSION: 290.0.1
  SNOWSQL_VERSION: 1.2.13
  SNOWSQL: ~/snowflake/snowsql
  SNOWSQL_DEST: ~/snowflake
  SNOWSQL_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SF_USERNAME }}
  SNOWSQL_PWD: ${{ secrets.SF_PASSWORD }}
  SF_DATABASEID: SFCARTOCI
  SF_SCHEMA_PREFIX: ci_${{ github.sha }}_${{ github.run_id }}

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Check if fork pull request can run CI
        if: github.event_name == 'pull_request_target'
        run: |
           if [[ "${{ github.event.action == 'labeled' && github.event.label.name == 'run_ci' }}" == "true" ]]; then
             echo "Fork pull request was labeled: ${{github.event.label.name}} by ${{ github.event.sender.login }}"
           else
             echo "Fork pull request needs to be verified by CARTO member then labeled with run_ci"
             exit 1
           fi
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get environment
        run: |
          source tools/dev_environment.sh.sample
          env >> $GITHUB_ENV
      - name: Install snowsql                          
        run: | 
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-${{env.SNOWSQL_VERSION}}-linux_x86_64.bash
      - name: Build
        run: make
      - name: Run integration tests
        run: make check-integration
