--------------------------------
-- Copyright (C) 2025 CARTO
--------------------------------

CREATE OR REPLACE EXTERNAL FUNCTION @@SCHEMA@@.__GENERATEPOINTS(
    geom VARCHAR(MAX),
    npoints INTEGER
)
RETURNS VARCHAR(MAX)
VOLATILE
LAMBDA '@@LAMBDA_ARN@@'
IAM_ROLE '@@IAM_ROLE_ARN@@'
MAX_BATCH_ROWS @@MAX_BATCH_ROWS@@;

CREATE OR REPLACE FUNCTION @@SCHEMA@@.ST_GENERATEPOINTS(geom GEOMETRY, npoints INTEGER)
RETURNS VARCHAR(MAX)
VOLATILE
AS $$
    SELECT @@SCHEMA@@.__GENERATEPOINTS(ST_ASGEOJSON($1), $2)
$$ LANGUAGE sql;
